packages:
  - 'backend'
  - 'web'
  - 'mobile'
  - 'infra'
  - 'libs/*'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - 'esbuild'
  - 'nx'
  - 'sharp'
  - 'unrs-resolver'
